4RTools/4RTools

App.config, Forms/AHKForm.cs, Forms/AutopotForm.Designer.cs, Forms/AutopotForm.cs, Forms/Container.Designer.cs, Forms/Container.resx, Utils/Config.cs
=> feat(AutoPot): add number up/down and remove the unused big logo file

Forms/AutopotForm.cs, Forms/Container.Designer.cs, Forms/Container.cs, Forms/Container.resx
- New Layout
- New button ON/OFF
- Placeholder for the character name(to do: update based on the memory address)
=> feat(Container): layout enhancements

4RTools.csproj, Forms/AHKForm.cs, Forms/AutopotForm.cs, Forms/Container.Designer.cs, Forms/Container.cs, Model/Autopot.cs, Model/Hexed.cs, Program.cs, Utils/Config.cs
- Add method to read memory and parse value to String that ends with nulls (0 on ASC TABLE)
- Moving configs to `Utils/Config.cs`
Related to #10
=> Chore: Render character name in UI when process is correctly loaded

Forms/Container.cs, Model/Autopot.cs
- Calling PostMessage only when Key != None
#7
=> fix: Not sending message to memory when Key is None

Forms/Container.cs, Forms/ProfileForm.Designer.cs, Forms/ProfileForm.cs
=> feat(Forms/ProfileForm): UI enhancement and prevent from delete the default profile

Forms/SkillAutoBuffForm.cs, Forms/StuffAutoBuffForm.cs
- Fix : Removing mouse wheel handler in combo box in Autobuff windows.
=> Fix: Remove mouse wheel handler in comboBox

Forms/SkillAutoBuffForm.Designer.cs, Forms/SkillAutoBuffForm.cs, Forms/SkillAutoBuffForm.resx, Forms/StuffAutoBuffForm.Designer.cs
Relative To #34 
Changes to vertical scroll in Autobuff Skill Tab
=> chore: Changing to scroll vertical in Autobuff Skills tab

Forms/Container.cs
#35 
Load default profile always when container load.
=> chore: Load default profile first always

Model/Macro.cs
Fix: Adding verification to not press None key in macro.
=> fix: Macro verify None key to not press

Forms/Container.cs
Update character name on profile change or turn ON/OFF
- Container as observer
- Update text label with the character name
=> feat(ContainerForm): update character name

Forms/AHKForm.Designer.cs, Forms/AHKForm.cs, Model/AHK.cs
- Adding check input to toggle Mouse Flick
Close #62
=> feat: Adding check to toggle mouse flick in AHK

Forms/SkillAutoBuffForm.cs, Forms/StuffAutoBuffForm.cs, Model/Autobuff.cs, Utils/FormUtils.cs, Utils/RObserver.cs
Do not add invalid keys to buff mapping. Ignore keys back, esc and None.
=> refactor(Autobuff): only add valid keys to the buffMapping

Forms/StuffAutoBuffForm.Designer.cs
=> fix: Coldproof input name

Forms/Container.cs, Forms/ToggleApplicationStateForm.cs, Utils/RObserver.cs
- Adding contextual menu to close 4R directly in system tray.
=> feat: Contextual Menu in system tray

Forms/MacroSongForm.Designer.cs, Forms/StuffAutoBuffForm.Designer.cs, Forms/StuffAutoBuffForm.resx, Utils/EffectStatusIDs.cs
=> feat(StuffAutoBuffForm): add Abrasive item auto buff

Model/Hexed.cs
- Using dictionary to classify Server and prevent address clash
=> improve: Using dictionary to prevent clash addresses in clients

Forms/AHKForm.cs, Forms/ATKDEFForm.cs, Forms/AutopotForm.cs, Forms/Container.cs, Forms/SkillAutoBuffForm.cs, Forms/StatusEffectForm.cs, Forms/StuffAutoBuffForm.cs, Forms/ToggleApplicationStateForm.cs, Model/AHK.cs, Model/Profile.cs
- Removing all instances in Form
- Using Profile Singleton instance as SSOT
=> refactor: Using profile as SSOT

Forms/MacroSongForm.cs, Forms/MacroSwitchForm.Designer.cs, Forms/MacroSwitchForm.cs, Forms/MacroSwitchForm.resx, Model/Macro.cs, Model/Profile.cs, Utils/FormUtils.cs
This PR implements the Form's logic to update and run the macro switch with the new chains' config.
- Add `MacroSwitch` to the profile singleton
- Save/update profile based on the form
- Add a new entry point to store all the macro switch data
-
=> feat(Forms/MacroSwitch): integrate form with the Macro Switch model

Model/Hexed.cs
- Using List instead of dictionary due servers with same process name
- Now we can have two process with same name and different addresses without clash (yay)
=> Using List instead of dictionary due servers with same process name

supported_servers.json
just adding  support for allstar ro , the hp & name address
=> Adding Support to AllstarRo client

supported_servers.json
by request from Iruga#9656 over discord
=> added support to ikoro

Forms/ClientUpdaterForm.cs, Forms/Container.cs, Model/Hexed.cs, supported_servers.json
This PR implements what is described in #96.
**Before this PR is merged:**
It is required to update https://raw.githubusercontent.com/4RTools/4RTools/main/supported_servers.json to add a property that's the game process's name.
=> Filter only accepted processes in Process comboBox

supported_servers.json
see PR about why ikoro doesnt work even with the addresses #122
=> removing ikoRO+ updating nameaddress for allstarRO

Resources/supported_servers.txt, supported_servers.json
[fix] Update the server.txt file
[fix] Fix the char name address for the remember RO
=> fix(supported_servers): fix remember Ro char name address

Resources/supported_servers.txt, supported_servers.json
Site: sealserver.cl
Discord: https://discord.gg/T6mzt9UD
=> feat(supported_servers): add Seal RO sealserver.cl

Resources/supported_servers.txt, supported_servers.json
Site: https://primeragnarok.com.br/
=> chore(supported_servers): add Prime Ragnarok Online server

Resources/supported_servers.txt, supported_servers.json
Site: http://x-ragnarok.com.br/
=> chore(supported_servers): add x-RO mid Rates server

Resources/supported_servers.txt, supported_servers.json
=> chore(supported_servers): add Nova RO server

Resources/supported_servers.txt, supported_servers.json
Site: https://annix.ragnarok-online.net/
=> feat(supported_servers): add Annix RO

Resources/supported_servers.txt, supported_servers.json
http://solid.ragnarok-online.net/
=> chore(supported_servers): add solid RO

Model/Autobuff.cs
This PR fix the list index off the auto-buff list and also increase the delay to 300ms.
=> fix(Autobuff): fix autobuff list and increase the delay

Model/StatusRecovery.cs, Resources/supported_servers.txt, supported_servers.json
This PR applies the same fix as the auto-buff for the status reco and remove xRO duplications in the supported.json
=> fix(xRO): fix status recovery

supported_servers.json
=> Adding RagnaWar support
